name: BotCity CI/CD - Update & Deploy

on:
  workflow_run:
    workflows: ["Code Review"]
    branches:
      - botcity-dev
      - main
    types:
      - completed

jobs:
  deploy-and-release:
    name: Deploy and release in BotCity
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get next version from tags
        id: version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "v1.0.0")
          echo "Última versão: $LAST_TAG"
          IFS='.' read -r major minor patch <<< "${LAST_TAG#v}"
          patch=$((patch + 1))
          NEW_TAG="v$major.$minor.$patch"
          echo "Nova versão: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create and push new tag (only for main branch)
        if: github.event.workflow_run.head_branch == 'main'
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Give execute permission to build.sh
        run: chmod +x build.sh

      - name: Execute build
        run: ./build.sh

      - name: Update in BotCity (botcity-dev)
        if: github.event.workflow_run.head_branch == 'botcity-dev'
        uses: botcity-dev/botcity-action-bots@v1.0.6
        with:
          deploy: false
          update: true
          release: true
          version: "1.2.4-T"
          botId: 'botcity-rpa-template'
          technology: 'python'
          botPath: './botcity-actions.zip'
        env:
          LOGIN: ${{ secrets.LOGIN }}
          SERVER: ${{ secrets.SERVER }}
          KEY: ${{ secrets.KEY }}

      - name: Deploy to BotCity (main)
        if: github.event.workflow_run.head_branch == 'main'
        uses: botcity-dev/botcity-action-bots@v1.0.6
        with:
          deploy: true
          update: false
          release: true
          version: "${{ env.NEW_TAG }}"
          botId: 'botcity-rpa-template'
          technology: 'python'
          botPath: './botcity-actions.zip'
        env:
          LOGIN: ${{ secrets.LOGIN }}
          SERVER: ${{ secrets.SERVER }}
          KEY: ${{ secrets.KEY }}